# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('contenidoNeto', models.PositiveIntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, height_field='ancho_imagen', null=True, upload_to='img_promocion', width_field='alto_imagen')),
                ('alto_imagen', models.IntegerField(default=0)),
                ('ancho_imagen', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioBasico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('duracion', models.IntegerField(default=0)),
                ('insumos', models.ManyToManyField(to='gestion.Insumo')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Sector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='promocion',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Sector'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='servicios',
            field=models.ManyToManyField(to='gestion.ServicioBasico'),
        ),
    ]
