# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-03 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviciobasico',
            name='duracion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviciobasico',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
