# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='insumos',
            field=models.ManyToManyField(to='gestion.Insumo'),
        ),
    ]
