# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(default='assets/img/promos/promo1.jpg', upload_to='assets/img/promos/'),
        ),
    ]
