# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20161104_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='alto_imagen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ancho_imagen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, height_field='ancho_imagen', null=True, upload_to='img_promocion', width_field='alto_imagen'),
        ),
    ]
