# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20161104_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='alto_imagen',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='ancho_imagen',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='contenidoNeto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
