# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20161119_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidadDeMedida',
            field=models.CharField(choices=[('Minilitros', 'Minilitros'), ('Litros', 'Litros'), ('Gramos', 'Gramos'), ('Kilos', 'Kilos'), ('Centimetros Cubicos', 'Centimetros Cubicos')], default=0, max_length=25),
        ),
    ]
