# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20161120_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidadDeMedida',
            field=models.CharField(choices=[('Mililitros', 'Mililitros'), ('Litros', 'Litros'), ('Gramos', 'Gramos'), ('Kilos', 'Kilos'), ('Centimetros Cubicos', 'Centimetros Cubicos')], default=0, max_length=25),
        ),
    ]
