# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoFijo',
            fields=[
                ('turno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turnos.Turno')),
                ('fecha_fin', models.DateTimeField()),
                ('turno_siguiente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='turnos.TurnoFijo')),
            ],
            bases=('turnos.turno',),
        ),
        migrations.AddField(
            model_name='turno',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Cliente'),
        ),
        migrations.AddField(
            model_name='turno',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Empleado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='promociones',
            field=models.ManyToManyField(to='gestion.Promocion'),
        ),
        migrations.AddField(
            model_name='turno',
            name='servicios',
            field=models.ManyToManyField(to='gestion.ServicioBasico'),
        ),
    ]
