# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-25 01:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='dia',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
