# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_auto_20170321_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='dia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
