# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-25 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_auto_20170325_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
