# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-25 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_auto_20170321_1714'),
        ('turnos', '0002_auto_20170325_0141'),
    ]

    operations = [
    ]
