# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-25 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_merge_20170325_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='dia',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2017, 3, 25, 17, 17, 36, 372916)),
        ),
    ]
