# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-25 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_auto_20170325_1717'),
        ('turnos', '0006_auto_20170325_1718'),
    ]

    operations = [
    ]
