# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test@test.com', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Duenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porc_comicion', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('localidad', models.CharField(max_length=100, null=True)),
                ('Duenia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.Duenia')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.Cliente')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.Empleado')),
            ],
        ),
    ]
