# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-25 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='fecha_liquidacion',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
