# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-03 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='porc_comision',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
