# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='monto',
            field=models.FloatField(null=True),
        ),
    ]
