# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20161128_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comision',
            old_name='fecha',
            new_name='fecha_liquidacion',
        ),
    ]
